RoboDex (Capstone)/Controllers/RoboDexerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.AspNetCore.Razor.Language.Extensions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Internal;
using RoboDex__Capstone_.Contracts;
using RoboDex__Capstone_.Models;
using RoboDex__Capstone_.Models.ViewModels;

namespace RoboDex__Capstone_.Controllers
{
    public class RoboDexerController : Controller
    {
        private IRepositoryWrapper _repo;


        public RoboDexerController(IRepositoryWrapper repo)
        {
            _repo = repo;
        }
        // GET: RoboDexerController
        public ActionResult Index()
        {           
            var roboDexerUser = FindLoggedInRoboDexer();
            if (roboDexerUser == null)
            {
                return RedirectToAction("Create");
            }
            NavLayout();
            var userName = _repo.RoboDexer.FindByCondition(r => r.UserName == roboDexerUser.UserName).SingleOrDefault();

            //This section finds the list to return to index view by multiple factors.
            var shoppingCart = FindItemsInShoppingCart();
            var tags = FindTagsFromItems(shoppingCart);

            var followers = CheckForPeopleDexerFollows();
            var followersItems = FindAllFollowersItems(followers);
            var tags2 = FindTagsInFollowersItems(followersItems);

            var finalListTags = MatchTagsFromCartWithTagsFromFollowersItems(tags, tags2);
            var items1 = FindFinalListOfItemsToReturnFromTags(finalListTags);//return this to master

            var newItems = FindNewItemsFromFollowers(followers);
            var finalListItems = CompareNewItemsWithItemsFromTags(newItems, items1);
            var itemsForView = CheckIfListOfItemsCountIsEnough(finalListItems);
            var listDevisibleByThree = MakeListDivisibleByThree(itemsForView);
            return View(listDevisibleByThree);
        }

        private List<Items> MakeListDivisibleByThree(List<Items> itemsForView)
        {
            var count = itemsForView.Count;
            var modulus = count % 3;
            List<Items> items = new List<Items>();
            for(int i = 0; i < count - modulus; i++)
            {
                items.Add(itemsForView[i]);
            }
              return items;
        }
       
        // GET: RoboDexerController/Details/5
        public ActionResult Details(int id)
        {
            NavLayout();
            var roboDexerUser = FindLoggedInRoboDexer();
            if (id == 0)
            {
                
                return View(roboDexerUser);
            }

            var item = _repo.Items.FindByCondition(i => i.ItemId == id).FirstOrDefault();
            var inventory = _repo.Inventory.FindByCondition(l => l.ItemId == item.ItemId).SingleOrDefault();
            var roboDexer = _repo.RoboDexer.FindByCondition(r => r.RoboDexerId == inventory.RoboDexerId).SingleOrDefault();
            
            if(roboDexer.RoboDexerId != roboDexerUser.RoboDexerId)
            {
                var dexerId = roboDexer.RoboDexerId;
                return RedirectToAction("SellerProfileInfo", new { id = dexerId });
            }
            return View(roboDexer);
        }

        public ActionResult EditProfile(int id)
        {
            var roboDexer = _repo.RoboDexer.FindByCondition(r => r.RoboDexerId == id).FirstOrDefault();

            return View(roboDexer);


        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditProfile(RoboDexer roboDexer)
        {
            _repo.RoboDexer.Update(roboDexer);
            _repo.Save();

            return RedirectToAction("Index");
        }

        public ActionResult SellerProfileInfo(int id)
        {
            var roboDexer = _repo.RoboDexer.FindByCondition(r => r.RoboDexerId == id).SingleOrDefault();
            return View(roboDexer);
        }

        public ActionResult ItemDetails (int id)
        {
            NavLayout();
            var roboDexerUser = FindLoggedInRoboDexer();
            var item = _repo.Items.FindByCondition(i => i.ItemId == id).SingleOrDefault();
            var inventory = _repo.Inventory.FindByCondition(i => i.ItemId == id).SingleOrDefault();
            var itemOwner = _repo.RoboDexer.FindByCondition(r => r.RoboDexerId == inventory.RoboDexerId).FirstOrDefault();

            var itemToReturn = ConvertItemToItemTagsLocation(item);
            if (roboDexerUser.RoboDexerId == itemOwner.RoboDexerId)
            {

                return View(itemToReturn);
            }
            else
            {
                return  RedirectToAction("SellerItemDetails", new { id });
            }

        }

        public ActionResult SellerItemDetails(int id)
        {
            NavLayout();
            var item = _repo.Items.FindByCondition(i => i.ItemId == id).SingleOrDefault();
           
            var itemToReturn = ConvertItemToItemTagsLocation(item);
            
            return View(itemToReturn);
        }      

        // GET: RoboDexerController/Create
        public ActionResult Create()
        {
            //NavLayout();
            RoboDexer roboDexer = new RoboDexer();
            return View(roboDexer);
        }

        // POST: RoboDexerController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RoboDexer robodexer)
        {
            //NavLayout();
            if (ModelState.IsValid)
            {
                var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
                robodexer.IdentityUserId = userId;
                
                _repo.RoboDexer.Create(robodexer);
                _repo.Save();
            }

            robodexer.InboxId = robodexer.RoboDexerId;
            robodexer.InventoryId = robodexer.RoboDexerId;
            robodexer.ShoppingCartId = robodexer.RoboDexerId;
            _repo.Save();
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: RoboDexerController/Edit/5
        public ActionResult EditItem(int id)
        {
            NavLayout();
            ItemTagsLocation itemToEnterIntoView = new ItemTagsLocation();

            var itemToEdit = _repo.Items.FindByCondition(i => i.ItemId == id).SingleOrDefault();
            itemToEnterIntoView.Items = itemToEdit;

            var locationToEdit = _repo.LocationPlace.FindByCondition(l => l.LocationId == itemToEdit.LocationId).SingleOrDefault();
            itemToEnterIntoView.LocationPlace = locationToEdit;

            var itemTags = _repo.ItemTags.FindByCondition(i => i.ItemId == itemToEdit.ItemId).ToList();

            List<Tags> listOfTags = new List<Tags>();
            foreach(ItemTags itemtag in itemTags)
            {
                var tags = _repo.Tags.FindByCondition(t => t.TagId == itemtag.TagsId).SingleOrDefault();
                listOfTags.Add(tags);
            }
            itemToEnterIntoView.Tags = listOfTags;
            //itemToEnterIntoView.Tags = tagsToEdit;

            return View(itemToEnterIntoView);
        }

        // POST: RoboDexerController/Edit/5
        [HttpPost, ActionName("EditItem")]
        [ValidateAntiForgeryToken]
        public ActionResult EditTheItem(int id, ItemTagsLocation itemTagsLocation)
        {
            NavLayout();
            var itemToEdit = _repo.Items.FindByCondition(i => i.ItemId == id).SingleOrDefault();
            itemToEdit = itemTagsLocation.Items;
            _repo.Items.Update(itemToEdit);

            var locationToEdit = _repo.LocationPlace.FindByCondition(l => l.LocationId == itemToEdit.LocationId).SingleOrDefault();
            locationToEdit = itemTagsLocation.LocationPlace;
            _repo.LocationPlace.Update(locationToEdit);

            ItemTags itemTags = new ItemTags();
            foreach(Tags tag in itemTagsLocation.Tags)
            {
                var items = _repo.ItemTags.FindByCondition(i => i.TagsId == tag.TagId).SingleOrDefault();
                var tagToEdit = _repo.Tags.FindByCondition(t => t.TagId == items.TagsId).SingleOrDefault();
                tagToEdit.Name = tag.Name;
                _repo.Tags.Update(tagToEdit);
            }

            _repo.Save();
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: RoboDexerController/Delete/5
        public async Task<ActionResult> DeleteItem(int id)
        {
            NavLayout();
            var itemTODelete = await _repo.Items.FindByCondition(i => i.ItemId == id).SingleOrDefaultAsync();
            
            if(itemTODelete == null)
            {
                return NotFound();
            }

            return View(itemTODelete);
        }

        // POST: RoboDexerController/Delete/5
        [HttpPost, ActionName("DeleteItem")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id)
        {
            NavLayout();
            var itemToDelete = await _repo.Items.FindByCondition(i => i.ItemId == id).SingleOrDefaultAsync();
            _repo.Items.Delete(itemToDelete);
            _repo.Save();
         
            return RedirectToAction(nameof(Index));         
        }

        public async Task<IActionResult> MessageRead(int Id)
        {
            NavLayout();
            var message = await _repo.Inbox.FindByCondition(i => i.Id == Id).SingleOrDefaultAsync();
            message.isRead = true;
            _repo.Inbox.Update(message);
            _repo.Save();
            return RedirectToAction("UpdateInbox");

RoboDex (Capstone)/Views/Shared/_Layout.cshtml
@*@model IEnumerable<RoboDex__Capstone_.Models.Inbox>*@
@{ 
    ViewBag.Title = "NavLayout";
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RoboDex__Capstone_</title>
    <link rel="icon" type="image/png" href="~/Dexter.jpg" sizes="60x60">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body style="background-color: lightsteelblue">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container" >
                <a class="navbar-brand" asp-area="" asp-controller="RoboDexer" asp-action="Index">RoboDex</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RoboDexer" asp-action="Details">Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RoboDexer" asp-action="ShoppingCart">Shopping Cart</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RoboDexer" asp-action="UpdateInbox">
                                Messages  @ViewBag.UserCount 


                                @*<h2>@ViewBag.UserCount  </h2>*@
                                @*@Model.Where(m => m.isRead == false).ToList().Count();*@
                            </a>




                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="colorbkg">
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2020 - RoboDex__Capstone_ - <a asp-area="" asp-controller="RoboDexer" asp-action="Details">Profile</a>
            </div>
        </footer>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script type="text/javascript">
                    //var count = Model.Count;

        </script>
        @RenderSection("Scripts", required: false)
    </div>
</body>
</html>